package ro.westaco.carhome.utils

import ro.westaco.carhome.R

class CountryCityUtils {

    companion object {

        fun getFlagDrawableResId(lettercode: String): Int {

            return when (lettercode) {

                "af" -> R.drawable.flag_afghanistan
                "al" -> R.drawable.flag_albania
                "dz" -> R.drawable.flag_algeria
                "ad" -> R.drawable.flag_andorra
                "ao" -> R.drawable.flag_angola
                "aq" -> R.drawable.flag_antarctica
                "ar" -> R.drawable.flag_argentina
                "am" -> R.drawable.flag_armenia
                "aw" -> R.drawable.flag_aruba
                "au" -> R.drawable.flag_australia
                "at" -> R.drawable.flag_austria
                "az" -> R.drawable.flag_azerbaijan
                "bh" -> R.drawable.flag_bahrain
                "bd" -> R.drawable.flag_bangladesh
                "by" -> R.drawable.flag_belarus
                "be" -> R.drawable.flag_belgium
                "bz" -> R.drawable.flag_belize
                "bj" -> R.drawable.flag_benin
                "bt" -> R.drawable.flag_bhutan
                "bo" -> R.drawable.flag_bolivia
                "ba" -> R.drawable.flag_bosnia
                "bw" -> R.drawable.flag_botswana
                "br" -> R.drawable.flag_brazil
                "bn" -> R.drawable.flag_brunei
                "bg" -> R.drawable.flag_bulgaria
                "bf" -> R.drawable.flag_burkina_faso
                "mm" -> R.drawable.flag_myanmar
                "bi" -> R.drawable.flag_burundi
                "kh" -> R.drawable.flag_cambodia
                "cm" -> R.drawable.flag_cameroon
                "ca" -> R.drawable.flag_canada
                "cv" -> R.drawable.flag_cape_verde
                "cf" -> R.drawable.flag_central_african_republic
                "td" -> R.drawable.flag_chad
                "cl" -> R.drawable.flag_chile
                "cn" -> R.drawable.flag_china
                "cx" -> R.drawable.flag_christmas_island
                "cc" -> R.drawable.flag_cocos // custom
                "co" -> R.drawable.flag_colombia
                "km" -> R.drawable.flag_comoros
                "cg" -> R.drawable.flag_republic_of_the_congo
                "cd" -> R.drawable.flag_democratic_republic_of_the_congo
                "ck" -> R.drawable.flag_cook_islands
                "cr" -> R.drawable.flag_costa_rica
                "hr" -> R.drawable.flag_croatia
                "cu" -> R.drawable.flag_cuba
                "cw" -> R.drawable.flag_curacao
                "cy" -> R.drawable.flag_cyprus
                "cz" -> R.drawable.flag_czech_republic
                "dk" -> R.drawable.flag_denmark
                "dj" -> R.drawable.flag_djibouti
                "tl" -> R.drawable.flag_timor_leste
                "ec" -> R.drawable.flag_ecuador
                "eg" -> R.drawable.flag_egypt
                "sv" -> R.drawable.flag_el_salvador
                "gq" -> R.drawable.flag_equatorial_guinea
                "er" -> R.drawable.flag_eritrea
                "ee" -> R.drawable.flag_estonia
                "et" -> R.drawable.flag_ethiopia
                "fk" -> R.drawable.flag_falkland_islands
                "fo" -> R.drawable.flag_faroe_islands
                "fj" -> R.drawable.flag_fiji
                "fi" -> R.drawable.flag_finland
                "fr" -> R.drawable.flag_france
                "pf" -> R.drawable.flag_french_polynesia
                "ga" -> R.drawable.flag_gabon
                "gm" -> R.drawable.flag_gambia
                "ge" -> R.drawable.flag_georgia
                "de" -> R.drawable.flag_germany
                "gh" -> R.drawable.flag_ghana
                "gi" -> R.drawable.flag_gibraltar
                "gr" -> R.drawable.flag_greece
                "gl" -> R.drawable.flag_greenland
                "gt" -> R.drawable.flag_guatemala
                "gn" -> R.drawable.flag_guinea
                "gw" -> R.drawable.flag_guinea_bissau
                "gy" -> R.drawable.flag_guyana
                "gf" -> R.drawable.flag_guyane
                "ht" -> R.drawable.flag_haiti
                "hn" -> R.drawable.flag_honduras
                "hk" -> R.drawable.flag_hong_kong
                "hu" -> R.drawable.flag_hungary
                "in" -> R.drawable.flag_india
                "id" -> R.drawable.flag_indonesia
                "ir" -> R.drawable.flag_iran
                "iq" -> R.drawable.flag_iraq
                "ie" -> R.drawable.flag_ireland
                "im" -> R.drawable.flag_isleof_man // custom
                "il" -> R.drawable.flag_israel
                "it" -> R.drawable.flag_italy
                "ci" -> R.drawable.flag_cote_divoire
                "jp" -> R.drawable.flag_japan
                "jo" -> R.drawable.flag_jordan
                "kz" -> R.drawable.flag_kazakhstan
                "ke" -> R.drawable.flag_kenya
                "ki" -> R.drawable.flag_kiribati
                "kw" -> R.drawable.flag_kuwait
                "kg" -> R.drawable.flag_kyrgyzstan
                "ky" -> R.drawable.flag_cayman_islands
                "la" -> R.drawable.flag_laos
                "lv" -> R.drawable.flag_latvia
                "lb" -> R.drawable.flag_lebanon
                "ls" -> R.drawable.flag_lesotho
                "lr" -> R.drawable.flag_liberia
                "ly" -> R.drawable.flag_libya
                "li" -> R.drawable.flag_liechtenstein
                "lt" -> R.drawable.flag_lithuania
                "lu" -> R.drawable.flag_luxembourg
                "mo" -> R.drawable.flag_macao
                "mk" -> R.drawable.flag_macedonia
                "mg" -> R.drawable.flag_madagascar
                "mw" -> R.drawable.flag_malawi
                "my" -> R.drawable.flag_malaysia
                "mv" -> R.drawable.flag_maldives
                "ml" -> R.drawable.flag_mali
                "mt" -> R.drawable.flag_malta
                "mh" -> R.drawable.flag_marshall_islands
                "mr" -> R.drawable.flag_mauritania
                "mu" -> R.drawable.flag_mauritius
                "yt" -> R.drawable.flag_martinique // no exact flag found
                "re" -> R.drawable.flag_martinique // no exact flag found
                "mq" -> R.drawable.flag_martinique
                "mx" -> R.drawable.flag_mexico
                "fm" -> R.drawable.flag_micronesia
                "md" -> R.drawable.flag_moldova
                "mc" -> R.drawable.flag_monaco
                "mn" -> R.drawable.flag_mongolia
                "me" -> R.drawable.flag_of_montenegro // custom
                "ma" -> R.drawable.flag_morocco
                "mz" -> R.drawable.flag_mozambique
                "na" -> R.drawable.flag_namibia
                "nr" -> R.drawable.flag_nauru
                "np" -> R.drawable.flag_nepal
                "nl" -> R.drawable.flag_netherlands
                "an" -> R.drawable.flag_netherlands_antilles
                "nc" -> R.drawable.flag_new_caledonia // custom
                "nz" -> R.drawable.flag_new_zealand
                "ni" -> R.drawable.flag_nicaragua
                "ne" -> R.drawable.flag_niger
                "ng" -> R.drawable.flag_nigeria
                "nu" -> R.drawable.flag_niue
                "kp" -> R.drawable.flag_north_korea
                "no" -> R.drawable.flag_norway
                "om" -> R.drawable.flag_oman
                "pk" -> R.drawable.flag_pakistan
                "pw" -> R.drawable.flag_palau
                "pa" -> R.drawable.flag_panama
                "pg" -> R.drawable.flag_papua_new_guinea
                "py" -> R.drawable.flag_paraguay
                "pe" -> R.drawable.flag_peru
                "ph" -> R.drawable.flag_philippines
                "pn" -> R.drawable.flag_pitcairn_islands
                "pl" -> R.drawable.flag_poland
                "pt" -> R.drawable.flag_portugal
                "pr" -> R.drawable.flag_puerto_rico
                "qa" -> R.drawable.flag_qatar
                "ro" -> R.drawable.flag_romania
                "ru" -> R.drawable.flag_russian_federation
                "rw" -> R.drawable.flag_rwanda
                "bl" -> R.drawable.flag_saint_barthelemy // custom
                "ws" -> R.drawable.flag_samoa
                "sm" -> R.drawable.flag_san_marino
                "st" -> R.drawable.flag_sao_tome_and_principe
                "sa" -> R.drawable.flag_saudi_arabia
                "sn" -> R.drawable.flag_senegal
                "rs" -> R.drawable.flag_serbia // custom
                "sc" -> R.drawable.flag_seychelles
                "sl" -> R.drawable.flag_sierra_leone
                "sg" -> R.drawable.flag_singapore
                "sx" -> R.drawable.flag_sint_marteen
                "sk" -> R.drawable.flag_slovakia
                "si" -> R.drawable.flag_slovenia
                "sb" -> R.drawable.flag_soloman_islands
                "so" -> R.drawable.flag_somalia
                "za" -> R.drawable.flag_south_africa
                "kr" -> R.drawable.flag_south_korea
                "es" -> R.drawable.flag_spain
                "lk" -> R.drawable.flag_sri_lanka
                "sh" -> R.drawable.flag_saint_helena // custom
                "pm" -> R.drawable.flag_saint_pierre
                "sd" -> R.drawable.flag_sudan
                "sr" -> R.drawable.flag_suriname
                "sz" -> R.drawable.flag_swaziland
                "se" -> R.drawable.flag_sweden
                "ch" -> R.drawable.flag_switzerland
                "sy" -> R.drawable.flag_syria
                "tw" -> R.drawable.flag_taiwan
                "tj" -> R.drawable.flag_tajikistan
                "tz" -> R.drawable.flag_tanzania
                "th" -> R.drawable.flag_thailand
                "tg" -> R.drawable.flag_togo
                "tk" -> R.drawable.flag_tokelau // custom
                "to" -> R.drawable.flag_tonga
                "tn" -> R.drawable.flag_tunisia
                "tr" -> R.drawable.flag_turkey
                "tm" -> R.drawable.flag_turkmenistan
                "tv" -> R.drawable.flag_tuvalu
                "ae" -> R.drawable.flag_uae
                "ug" -> R.drawable.flag_uganda
                "gb" -> R.drawable.flag_united_kingdom
                "ua" -> R.drawable.flag_ukraine
                "uy" -> R.drawable.flag_uruguay
                "us" -> R.drawable.flag_united_states_of_america
                "uz" -> R.drawable.flag_uzbekistan
                "vu" -> R.drawable.flag_vanuatu
                "va" -> R.drawable.flag_vatican_city
                "ve" -> R.drawable.flag_venezuela
                "vn" -> R.drawable.flag_vietnam
                "wf" -> R.drawable.flag_wallis_and_futuna
                "ye" -> R.drawable.flag_yemen
                "zm" -> R.drawable.flag_zambia
                "zw" -> R.drawable.flag_zimbabwe
                "ai" -> R.drawable.flag_anguilla
                "ag" -> R.drawable.flag_antigua_and_barbuda
                "bs" -> R.drawable.flag_bahamas
                "bb" -> R.drawable.flag_barbados
                "bm" -> R.drawable.flag_bermuda
                "vg" -> R.drawable.flag_british_virgin_islands
                "dm" -> R.drawable.flag_dominica
                "do" -> R.drawable.flag_dominican_republic
                "gd" -> R.drawable.flag_grenada
                "jm" -> R.drawable.flag_jamaica
                "ms" -> R.drawable.flag_montserrat
                "kn" -> R.drawable.flag_saint_kitts_and_nevis
                "lc" -> R.drawable.flag_saint_lucia
                "vc" -> R.drawable.flag_saint_vicent_and_the_grenadines
                "tt" -> R.drawable.flag_trinidad_and_tobago
                "tc" -> R.drawable.flag_turks_and_caicos_islands
                "vi" -> R.drawable.flag_us_virgin_islands
                "ss" -> R.drawable.flag_south_sudan
                "xk" -> R.drawable.flag_kosovo
                "is" -> R.drawable.flag_iceland
                "ax" -> R.drawable.flag_aland_islands
                "as" -> R.drawable.flag_american_samoa
                "io" -> R.drawable.flag_british_indian_ocean_territory
                "gp" -> R.drawable.flag_guadeloupe
                "gu" -> R.drawable.flag_guam
                "gg" -> R.drawable.flag_guernsey
                "je" -> R.drawable.flag_jersey
                "nf" -> R.drawable.flag_norfolk_island
                "mp" -> R.drawable.flag_northern_mariana_islands
                "ps" -> R.drawable.flag_palestian_territory
                "mf" -> R.drawable.flag_saint_martin
                "gs" -> R.drawable.flag_south_georgia
                "tf" -> R.drawable.flg_southern
                "bq" -> R.drawable.flg_bonaire
                "bv" -> R.drawable.flg_bouvet_island
                "eh" -> R.drawable.flag_western_sahara
                "hm" -> R.drawable.flag_australia
                "sj" -> R.drawable.flg_bouvet_island
                "um" -> R.drawable.flag_united_states_of_america
                else -> R.drawable.flag_somalia
            }
        }

        fun getFlagId(letterCode: String): String {

            return when (letterCode) {

                "af" -> "\uD83C\uDDE6\uD83C\uDDEB"
                "al" -> "\uD83C\uDDE6\uD83C\uDDF1"
                "dz" -> "\uD83C\uDDE9\uD83C\uDDFF"
                "ad" -> "\uD83C\uDDE6\uD83C\uDDE9"
                "ao" -> "\uD83C\uDDE6\uD83C\uDDF4"
                "aq" -> "\uD83C\uDDE6\uD83C\uDDF6"
                "ar" -> "\uD83C\uDDE6\uD83C\uDDF7"
                "am" -> "\uD83C\uDDE6\uD83C\uDDF2"
                "aw" -> "\uD83C\uDDE6\uD83C\uDDFC"
                "au" -> "\uD83C\uDDE6\uD83C\uDDFA"
                "at" -> "\uD83C\uDDE6\uD83C\uDDF9"
                "az" -> "\uD83C\uDDE6\uD83C\uDDFF"
                "bh" -> "\uD83C\uDDE7\uD83C\uDDED"
                "bd" -> "\uD83C\uDDE7\uD83C\uDDE9"
                "by" -> "\uD83C\uDDE7\uD83C\uDDFE"
                "be" -> "\uD83C\uDDE7\uD83C\uDDEA"
                "bz" -> "\uD83C\uDDE7\uD83C\uDDFF"
                "bj" -> "\uD83C\uDDE7\uD83C\uDDEF"
                "bt" -> "\uD83C\uDDE7\uD83C\uDDF9"
                "bo" -> "\uD83C\uDDE7\uD83C\uDDF4"
                "ba" -> "\uD83C\uDDE7\uD83C\uDDE6"
                "bw" -> "\uD83C\uDDE7\uD83C\uDDFC"
                "br" -> "\uD83C\uDDE7\uD83C\uDDF7"
                "bn" -> "\uD83C\uDDE7\uD83C\uDDF3"
                "bg" -> "\uD83C\uDDE7\uD83C\uDDEC"
                "bf" -> "\uD83C\uDDE7\uD83C\uDDEB"
                "mm" -> "\uD83C\uDDF2\uD83C\uDDF2"
                "bi" -> "\uD83C\uDDE7\uD83C\uDDEE"
                "kh" -> "\uD83C\uDDF0\uD83C\uDDED"
                "cm" -> "\uD83C\uDDE8\uD83C\uDDF2"
                "ca" -> "\uD83C\uDDE8\uD83C\uDDE6"
                "cv" -> "\uD83C\uDDE8\uD83C\uDDFB"
                "cf" -> "\uD83C\uDDE8\uD83C\uDDEB"
                "td" -> "\uD83C\uDDF9\uD83C\uDDE9"
                "cl" -> "\uD83C\uDDE8\uD83C\uDDF1"
                "cn" -> "\uD83C\uDDE8\uD83C\uDDF3"
                "cx" -> "\uD83C\uDDE8\uD83C\uDDFD"
                "cc" -> "\uD83C\uDDE8\uD83C\uDDE8"
                "co" -> "\uD83C\uDDE8\uD83C\uDDF4"
                "km" -> "\uD83C\uDDF0\uD83C\uDDF2"
                "cg" -> "\uD83C\uDDE8\uD83C\uDDEC"
                "cd" -> "\uD83C\uDDE8\uD83C\uDDE9"
                "ck" -> "\uD83C\uDDE8\uD83C\uDDF0"
                "cr" -> "\uD83C\uDDE8\uD83C\uDDF7"
                "hr" -> "\uD83C\uDDED\uD83C\uDDF7"
                "cu" -> "\uD83C\uDDE8\uD83C\uDDFA"
                "cw" -> "\uD83C\uDDE8\uD83C\uDDFC"
                "cy" -> "\uD83C\uDDE8\uD83C\uDDFE"
                "cz" -> "\uD83C\uDDE8\uD83C\uDDFF"
                "dk" -> "\uD83C\uDDE9\uD83C\uDDF0"
                "dj" -> "\uD83C\uDDE9\uD83C\uDDEF"
                "tl" -> "\uD83C\uDDF9\uD83C\uDDF1"
                "ec" -> "\uD83C\uDDEA\uD83C\uDDE8"
                "eg" -> "\uD83C\uDDEA\uD83C\uDDEC"
                "sv" -> "\uD83C\uDDF8\uD83C\uDDFB"
                "gq" -> "\uD83C\uDDEC\uD83C\uDDF6"
                "er" -> "\uD83C\uDDEA\uD83C\uDDF7"
                "ee" -> "\uD83C\uDDEA\uD83C\uDDEA"
                "et" -> "\uD83C\uDDEA\uD83C\uDDF9"
                "fk" -> "\uD83C\uDDEB\uD83C\uDDF0"
                "fo" -> "\uD83C\uDDEB\uD83C\uDDF4"
                "fj" -> "\uD83C\uDDEB\uD83C\uDDEF"
                "fi" -> "\uD83C\uDDEB\uD83C\uDDEE"
                "fr" -> "\uD83C\uDDEB\uD83C\uDDF7"
                "pf" -> "\uD83C\uDDF5\uD83C\uDDEB"
                "ga" -> "\uD83C\uDDEC\uD83C\uDDE6"
                "gm" -> "\uD83C\uDDEC\uD83C\uDDF2"
                "ge" -> "\uD83C\uDDEC\uD83C\uDDEA"
                "de" -> "\uD83C\uDDE9\uD83C\uDDEA"
                "gh" -> "\uD83C\uDDEC\uD83C\uDDED"
                "gi" -> "\uD83C\uDDEC\uD83C\uDDEE"
                "gr" -> "\uD83C\uDDEC\uD83C\uDDF7"
                "gl" -> "\uD83C\uDDEC\uD83C\uDDF1"
                "gt" -> "\uD83C\uDDEC\uD83C\uDDF9"
                "gn" -> "\uD83C\uDDEC\uD83C\uDDF3"
                "gw" -> "\uD83C\uDDEC\uD83C\uDDFC"
                "gy" -> "\uD83C\uDDEC\uD83C\uDDFE"
                "gf" -> "\uD83C\uDDEC\uD83C\uDDEB"
                "ht" -> "\uD83C\uDDED\uD83C\uDDF9"
                "hn" -> "\uD83C\uDDED\uD83C\uDDF3"
                "hk" -> "\uD83C\uDDED\uD83C\uDDF0"
                "hu" -> "\uD83C\uDDED\uD83C\uDDFA"
                "in" -> "\uD83C\uDDEE\uD83C\uDDF3"
                "id" -> "\uD83C\uDDEE\uD83C\uDDE9"
                "ir" -> "\uD83C\uDDEE\uD83C\uDDF7"
                "iq" -> "\uD83C\uDDEE\uD83C\uDDF6"
                "ie" -> "\uD83C\uDDEE\uD83C\uDDEA"
                "im" -> "\uD83C\uDDEE\uD83C\uDDF2"
                "il" -> "\uD83C\uDDEE\uD83C\uDDF1"
                "it" -> "\uD83C\uDDEE\uD83C\uDDF9"
                "ci" -> "\uD83C\uDDE8\uD83C\uDDEE"
                "jp" -> "\uD83C\uDDEF\uD83C\uDDF5"
                "jo" -> "\uD83C\uDDEF\uD83C\uDDF4"
                "kz" -> "\uD83C\uDDF0\uD83C\uDDFF"
                "ke" -> "\uD83C\uDDF0\uD83C\uDDEA"
                "ki" -> "\uD83C\uDDF0\uD83C\uDDEE"
                "kw" -> "\uD83C\uDDF0\uD83C\uDDFC"
                "kg" -> "\uD83C\uDDF0\uD83C\uDDEC"
                "ky" -> "\uD83C\uDDF0\uD83C\uDDFE"
                "la" -> "\uD83C\uDDF1\uD83C\uDDE6"
                "lv" -> "\uD83C\uDDF1\uD83C\uDDFB"
                "lb" -> "\uD83C\uDDF1\uD83C\uDDE7"
                "ls" -> "\uD83C\uDDF1\uD83C\uDDF8"
                "lr" -> "\uD83C\uDDF1\uD83C\uDDF7"
                "ly" -> "\uD83C\uDDF1\uD83C\uDDFE"
                "li" -> "\uD83C\uDDF1\uD83C\uDDEE"
                "lt" -> "\uD83C\uDDF1\uD83C\uDDF9"
                "lu" -> "\uD83C\uDDF1\uD83C\uDDFA"
                "mo" -> "\uD83C\uDDF2\uD83C\uDDF4"
                "mk" -> "\uD83C\uDDF2\uD83C\uDDF0"
                "mg" -> "\uD83C\uDDF2\uD83C\uDDEC"
                "mw" -> "\uD83C\uDDF2\uD83C\uDDFC"
                "my" -> "\uD83C\uDDF2\uD83C\uDDFE"
                "mv" -> "\uD83C\uDDF2\uD83C\uDDFB"
                "ml" -> "\uD83C\uDDF2\uD83C\uDDF1"
                "mt" -> "\uD83C\uDDF2\uD83C\uDDF9"
                "mh" -> "\uD83C\uDDF2\uD83C\uDDED"
                "mr" -> "\uD83C\uDDF2\uD83C\uDDF7"
                "mu" -> "\uD83C\uDDF2\uD83C\uDDFA"
                "yt" -> "\uD83C\uDDFE\uD83C\uDDF9"
                "re" -> "\uD83C\uDDF7\uD83C\uDDEA"
                "mq" -> "\uD83C\uDDF2\uD83C\uDDF6"
                "mx" -> "\uD83C\uDDF2\uD83C\uDDFD"
                "fm" -> "\uD83C\uDDEB\uD83C\uDDF2"
                "md" -> "\uD83C\uDDF2\uD83C\uDDE9"
                "mc" -> "\uD83C\uDDF2\uD83C\uDDE8"
                "mn" -> "\uD83C\uDDF2\uD83C\uDDF3"
                "me" -> "\uD83C\uDDF2\uD83C\uDDEA"
                "ma" -> "\uD83C\uDDF2\uD83C\uDDE6"
                "mz" -> "\uD83C\uDDF2\uD83C\uDDFF"
                "na" -> "\uD83C\uDDF3\uD83C\uDDE6"
                "nr" -> "\uD83C\uDDF3\uD83C\uDDF7"
                "np" -> "\uD83C\uDDF3\uD83C\uDDF5"
                "nl" -> "\uD83C\uDDF3\uD83C\uDDF1"
                "nc" -> "\uD83C\uDDF3\uD83C\uDDE8"
                "nz" -> "\uD83C\uDDF3\uD83C\uDDFF"
                "ni" -> "\uD83C\uDDF3\uD83C\uDDEE"
                "ne" -> "\uD83C\uDDF3\uD83C\uDDEA"
                "ng" -> "\uD83C\uDDF3\uD83C\uDDEC"
                "nu" -> "\uD83C\uDDF3\uD83C\uDDFA"
                "kp" -> "\uD83C\uDDF0\uD83C\uDDF5"
                "no" -> "\uD83C\uDDF3\uD83C\uDDF4"
                "om" -> "\uD83C\uDDF4\uD83C\uDDF2"
                "pk" -> "\uD83C\uDDF5\uD83C\uDDF0"
                "pw" -> "\uD83C\uDDF5\uD83C\uDDFC"
                "pa" -> "\uD83C\uDDF5\uD83C\uDDE6"
                "pg" -> "\uD83C\uDDF5\uD83C\uDDEC"
                "py" -> "\uD83C\uDDF5\uD83C\uDDFE"
                "pe" -> "\uD83C\uDDF5\uD83C\uDDEA"
                "ph" -> "\uD83C\uDDF5\uD83C\uDDED"
                "pn" -> "\uD83C\uDDF5\uD83C\uDDF3"
                "pl" -> "\uD83C\uDDF5\uD83C\uDDF1"
                "pt" -> "\uD83C\uDDF5\uD83C\uDDF9"
                "pr" -> "\uD83C\uDDF5\uD83C\uDDF7"
                "qa" -> "\uD83C\uDDF6\uD83C\uDDE6"
                "ro" -> "\uD83C\uDDF7\uD83C\uDDF4"
                "ru" -> "\uD83C\uDDF7\uD83C\uDDFA"
                "rw" -> "\uD83C\uDDF7\uD83C\uDDFC"
                "bl" -> "\uD83C\uDDE7\uD83C\uDDF1"
                "ws" -> "\uD83C\uDDFC\uD83C\uDDF8"
                "sm" -> "\uD83C\uDDF8\uD83C\uDDF2"
                "st" -> "\uD83C\uDDF8\uD83C\uDDF9"
                "sa" -> "\uD83C\uDDF8\uD83C\uDDE6"
                "sn" -> "\uD83C\uDDF8\uD83C\uDDF3"
                "rs" -> "\uD83C\uDDF7\uD83C\uDDF8"
                "sc" -> "\uD83C\uDDF8\uD83C\uDDE8"
                "sl" -> "\uD83C\uDDF8\uD83C\uDDF1"
                "sg" -> "\uD83C\uDDF8\uD83C\uDDEC"
                "sx" -> "\uD83C\uDDF8\uD83C\uDDFD"
                "sk" -> "\uD83C\uDDF8\uD83C\uDDF0"
                "si" -> "\uD83C\uDDF8\uD83C\uDDEE"
                "sb" -> "\uD83C\uDDF8\uD83C\uDDE7"
                "so" -> "\uD83C\uDDF8\uD83C\uDDF4"
                "za" -> "\uD83C\uDDFF\uD83C\uDDE6"
                "kr" -> "\uD83C\uDDF0\uD83C\uDDF7"
                "es" -> "\uD83C\uDDEA\uD83C\uDDF8"
                "lk" -> "\uD83C\uDDF1\uD83C\uDDF0"
                "sh" -> "\uD83C\uDDF8\uD83C\uDDED"
                "pm" -> "\uD83C\uDDF5\uD83C\uDDF2"
                "sd" -> "\uD83C\uDDF8\uD83C\uDDE9"
                "sr" -> "\uD83C\uDDF8\uD83C\uDDF7"
                "sz" -> "\uD83C\uDDF8\uD83C\uDDFF"
                "se" -> "\uD83C\uDDF8\uD83C\uDDEA"
                "ch" -> "\uD83C\uDDE8\uD83C\uDDED"
                "sy" -> "\uD83C\uDDF8\uD83C\uDDFE"
                "tw" -> "\uD83C\uDDF9\uD83C\uDDFC"
                "tj" -> "\uD83C\uDDF9\uD83C\uDDEF"
                "tz" -> "\uD83C\uDDF9\uD83C\uDDFF"
                "th" -> "\uD83C\uDDF9\uD83C\uDDED"
                "tg" -> "\uD83C\uDDF9\uD83C\uDDEC"
                "tk" -> "\uD83C\uDDF9\uD83C\uDDF0"
                "to" -> "\uD83C\uDDF9\uD83C\uDDF4"
                "tn" -> "\uD83C\uDDF9\uD83C\uDDF3"
                "tr" -> "\uD83C\uDDF9\uD83C\uDDF7"
                "tm" -> "\uD83C\uDDF9\uD83C\uDDF2"
                "tv" -> "\uD83C\uDDF9\uD83C\uDDFB"
                "ae" -> "\uD83C\uDDE6\uD83C\uDDEA"
                "ug" -> "\uD83C\uDDFA\uD83C\uDDEC"
                "gb" -> "\uD83C\uDDEC\uD83C\uDDE7"
                "ua" -> "\uD83C\uDDFA\uD83C\uDDE6"
                "uy" -> "\uD83C\uDDFA\uD83C\uDDFE"
                "us" -> "\uD83C\uDDFA\uD83C\uDDF8"
                "uz" -> "\uD83C\uDDFA\uD83C\uDDFF"
                "vu" -> "\uD83C\uDDFB\uD83C\uDDFA"
                "va" -> "\uD83C\uDDFB\uD83C\uDDE6"
                "ve" -> "\uD83C\uDDFB\uD83C\uDDEA"
                "vn" -> "\uD83C\uDDFB\uD83C\uDDF3"
                "wf" -> "\uD83C\uDDFC\uD83C\uDDEB"
                "ye" -> "\uD83C\uDDFE\uD83C\uDDEA"
                "zm" -> "\uD83C\uDDFF\uD83C\uDDF2"
                "zw" -> "\uD83C\uDDFF\uD83C\uDDFC"
                "ai" -> "\uD83C\uDDE6\uD83C\uDDEE"
                "ag" -> "\uD83C\uDDE6\uD83C\uDDEC"
                "bs" -> "\uD83C\uDDE7\uD83C\uDDF8"
                "bb" -> "\uD83C\uDDE7\uD83C\uDDE7"
                "bm" -> "\uD83C\uDDE7\uD83C\uDDF2"
                "vg" -> "\uD83C\uDDFB\uD83C\uDDEC"
                "dm" -> "\uD83C\uDDE9\uD83C\uDDF2"
                "do" -> "\uD83C\uDDE9\uD83C\uDDF4"
                "gd" -> "\uD83C\uDDEC\uD83C\uDDE9"
                "jm" -> "\uD83C\uDDEF\uD83C\uDDF2"
                "ms" -> "\uD83C\uDDF2\uD83C\uDDF8"
                "kn" -> "\uD83C\uDDF0\uD83C\uDDF3"
                "lc" -> "\uD83C\uDDF1\uD83C\uDDE8"
                "vc" -> "\uD83C\uDDFB\uD83C\uDDE8"
                "tt" -> "\uD83C\uDDF9\uD83C\uDDF9"
                "tc" -> "\uD83C\uDDF9\uD83C\uDDE8"
                "vi" -> "\uD83C\uDDFB\uD83C\uDDEE"
                "ss" -> "\uD83C\uDDF8\uD83C\uDDF8"
                "xk" -> "\uD83C\uDDFD\uD83C\uDDF0"
                "is" -> "\uD83C\uDDEE\uD83C\uDDF8"
                "ax" -> "\uD83C\uDDE6\uD83C\uDDFD"
                "as" -> "\uD83C\uDDE6\uD83C\uDDF8"
                "io" -> "\uD83C\uDDEE\uD83C\uDDF4"
                "gp" -> "\uD83C\uDDEC\uD83C\uDDF5"
                "gu" -> "\uD83C\uDDEC\uD83C\uDDFA"
                "gg" -> "\uD83C\uDDEC\uD83C\uDDEC"
                "je" -> "\uD83C\uDDEF\uD83C\uDDEA"
                "nf" -> "\uD83C\uDDF3\uD83C\uDDEB"
                "mp" -> "\uD83C\uDDF2\uD83C\uDDF5"
                "ps" -> "\uD83C\uDDF5\uD83C\uDDF8"
                "mf" -> "\uD83C\uDDF2\uD83C\uDDEB"
                "gs" -> "\uD83C\uDDEC\uD83C\uDDF8"
                "tf" -> "\uD83C\uDDF9\uD83C\uDDEB"
                "bq" -> "\uD83C\uDDE7\uD83C\uDDF6"
                "bv" -> "\uD83C\uDDE7\uD83C\uDDFB"
                "eh" -> "\uD83C\uDDEA\uD83C\uDDED"
                "hm" -> "\uD83C\uDDED\uD83C\uDDF2"
                "sj" -> "\uD83C\uDDF8\uD83C\uDDEF"
                "um" -> "\uD83C\uDDFA\uD83C\uDDF2"
                else -> "\uD83C\uDDF8\uD83C\uDDF4"
            }
        }

        fun firstTwo(str: String): String? {
            return if (str.length < 2) str else str.substring(0, 2)
        }

    }


}